name: test-build
on:
  push:
    branches:
      - main
jobs:
  test-lint-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: aravinthraaj/testreactapp@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # - name: Install dependencies
        #   run: npm install
        # - name: Generate build
        #   run: npm run build
        # # Share artifact inside workflow
        # - name: Share artifact inside workflow
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: react-github-actions-build
        #     path: build
        # - name: Deploy to netlify
        #   uses: netlify/actions/cli@master
        # env:
        #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # with:
        #   args: deploy --dir=build --prod
        #   secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
